export default {
  NEXT_PLAYER: 'NEXT_PLAYER',
  UPDATE_WORLD: 'UPDATE_WORLD',
  NEW_NUMBER: 'NEW_NUMBER',
  NEW_TURN: 'NEW_TURN',
  UPDATE_BASE: 'UPDATE_BASE',
  UPDATE_CURRENT_CASE: 'UPDATE_CURRENT_CASE'
}
